### ISSUE TITLE
Data dumps not working

### ISSUE THREAD

**Issue by sawernke** [LOGARANDES/gazetteer-demo#25]
Data dumps in http://logarandes.org/geo/browse.html (bottom of page: Other formats) are not translating correctly.

-The GeoJSON file does not read correctly in desktop GIS programs (e.g. QGIS). It looks like it might be missing some header/footer information? Not sure
-Same for KML. For example, Google Earth cannot open it.
-I have not tried Atom xml

**Comment by wsalesky** [comment]
Thanks, I will take a look.

**Comment by wsalesky** [comment]
@sawernke I am doing some code refactoring on Syriaca.org, and would like to port them over to LOGAR, I believe they should address this issue. Hopefully in the next week.

**Comment by sawernke** [comment]
Great, thanks, Winona. I'll be in touch.

**Comment by wsalesky** [comment]
Hi Steve, sorry about the delay. I have corrected both outputs and tested them.  
geoJSON tested here: http://geojsonlint.com/
and KML tested here: http://googlemapsapi.blogspot.com/2007/06/validate-your-kml-online-or-offline.html

Please let me know if you have any trouble loading them into your software.
