### ISSUE TITLE
Map zooming limited to regional scale. Unlimited zooming is preferred.

### ISSUE THREAD

**Issue by sawernke** [LOGARANDES/gazetteer-demo#5]
The map interface does not allow zooming in beyond a pretty large scale. This is true of both the overview map on the index page and individual place pages. Is there something in the embed code that is limiting the zoom range? As-is, it is not useful because we can’t zoom into the towns to seem them in the satellite image, only regional-scale zooming is possible. As I recall in the version before revisions, this wasn’t an issue.

**Comment by sawernke** [comment]
On my end, I still can't zoom in beyond regional scale.

**Comment by wsalesky** [comment]
Please try a hard refresh. If that does not work, let me know what place you are testing and what browser.

Thanks!

**Comment by sawernke** [comment]
Hard refresh worked! thanks.

**Comment by wsalesky** [comment]
Great!
