### ISSUE TITLE
Individual place page: map pane too small

### ISSUE THREAD

**Issue by sawernke** [LOGARANDES/gazetteer-demo#7]
Resizing map pane: individual place page: could the map be larger on both axes by 50%? Also, the zooming problem is present on these pages as well—one cannot zoom in beyond regional scale.

**Comment by wsalesky** [comment]
Would you like to move the text on the right of the map (location information) to below the map? Then it could take up that whole center column.

**Comment by sawernke** [comment]
Yes, that would be great--move text below. Thx!

**Comment by wsalesky** [comment]
How does this look?

**Comment by sawernke** [comment]
Much better--but how about even a bit bigger: about ~25% longer on Y axis?

**Comment by wsalesky** [comment]
Now? (I have it set to 60% of containing div height.)

**Comment by sawernke** [comment]
Yes that is great!

**Comment by wsalesky** [comment]
Okay.
